### ISSUE TITLE
no output detecetd

### ISSUE THREAD

**Issue by corbijonathan** [infspiredBAT/Circoletto#1]
Hi! 
Thanks for the script, seems really great! 
I experienced an issue though: everything seems to run correctly but after "running cicos", I had this error message:
"there was an error running Circos (no output detected), maybe try once more or something different? - exiting"
Should I indicate the path to the output? If so, I did not find an entry on the perl script... Sorry if the question is stupid but I am not a programer and first time user of Circos... 
Thanks for your advice, 
Jonathan

**Comment by nikosdarzentas** [comment]
Hi Jonathan,
Thank you for your kind words, and your message.

You're not giving me much to go on, but also there's some setting up you need to do (outlined in the README.md), e.g. install Circos and make sure the paths (e.g. $path2circos) in the code are updated. There's also a log output from Circos (ending in .circos.log), which might give you some clues. Finally, it might be your inputs - then I'd try them on the online Circoletto to see if they work there.

Let me know how it goes.

**Comment by corbijonathan** [comment]
Thanks for your reply. 
It seems to work great! Just a quick (sorry if stupid) question: it seems that the main hits are drawn in black and secondary hits (with lower e-values) are drawn in transparency. For the latter, lines are very faded. Where would be the parameters to decrease transparency? Thanks
