### ISSUE TITLE
Extracting data from Circoletto files

### ISSUE THREAD

**Issue by jrjhealey** [infspiredBAT/Circoletto#3]
Hi again Nikos,

Sorry to open up an issue for this but it seemed the easiest way to get in touch that I could find!

Just a fairly simple question hopefully:

Is there some way to access the data that forms the histograms in the final image? I'd like to 'rank' all the sequences in terms of the number of times they are represented in other sequences, which to me seems to be kind of functionally equivalent to finding the arcs with the largest/densest histograms? I could probably do it all from the original blast file, but that seems like a much more involved approach.

Are there some temporary output files or something which carry the histogram data I could parse maybe?

Cheers

Joe

**Comment by nikosdarzentas** [comment]
Hello!
Sorry, I missed the email notification (have now changed my filters...) and I'm not a regular on GitHub.
Maybe I'm late, but here we go.

There's a .his output file which has the histogram info, there's also .links with the ribbons ("arcs").
Offline you can access them directly, online you can click to see the BLAST output (under the output image thumbnail) and then add the extensions I mentioned (e.g. http://tools.bat.infspire.org/circoletto_results/cl0019511817.blasted.his) - I have a very old note to provide a tarball with all these files...

Hope I helped,
keep in touch (also at bat@infspire.org).

**Comment by jrjhealey** [comment]
OK great thanks Nikos! I must have missed the .his file amongst all the others!

I'll stop nagging you now ;)
