### ISSUE TITLE
Error running blastn

### ISSUE THREAD

**Issue by HTaekOppa** [infspiredBAT/Circoletto#4]
Hi,

Thank you for the good program.
After submitting this script 

source activate circoletto

perl /apps/Circoletto/circoletto.pl --query Nb_2Mb.fasta --database NbSoG --cpus 8 --out_dir Out2M_NbNb

source deactivate 

I have this error message saying (!) there was an error running blastn with your files - exiting.
Please see the attached file. 

Any recommendation on this matter?

Cheers,

Taek
[Cir2M_NbNb.txt](https://github.com/infspiredBAT/Circoletto/files/2230537/Cir2M_NbNb.txt)

**Comment by nikosdarzentas** [comment]
Hello Taek,
thanks for getting in touch.

This means there's a non-0 status when Circoletto tries to run BLAST with your inputs. My best advice is to try and run blastn outside Circoletto and try and troubleshoot from there.

Ciao.
